architecture: replicaset
useStatefulSet: true

enableIPv6: true
replicaCount: 3
podAntiAffinityPreset: hard
nodeAffinityPreset:
  type: "hard"
  key: "7tv.io/node-type"
  values:
    - database
tolerations:
  - key: "7tv.io/node-type"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
resources:
  requests:
    cpu: "16000m"
    memory: "64Gi"
  limits:
    cpu: "16000m"
    memory: "64Gi"

persistence:
  enabled: true
  name: "datadir"
  storageClass: "database"
  accessModes:
    - ReadWriteOnce
  size: 150Gi

arbiter:
  enabled: false

metrics:
  enabled: true
  collector:
    ## @param metrics.collector.all Enable all collectors. Same as enabling all individual metrics
    ## Enabling all metrics will cause significant CPU load on mongod
    all: false
    ## @param metrics.collector.diagnosticdata Boolean Enable collecting metrics from getDiagnosticData
    diagnosticdata: true
    ## @param metrics.collector.replicasetstatus Boolean Enable collecting metrics from replSetGetStatus
    replicasetstatus: true
    ## @param metrics.collector.dbstats Boolean Enable collecting metrics from dbStats
    dbstats: false
    ## @param metrics.collector.topmetrics Boolean Enable collecting metrics from top admin command
    topmetrics: false
    ## @param metrics.collector.indexstats Boolean Enable collecting metrics from $indexStats
    indexstats: false
    ## @param metrics.collector.collstats Boolean Enable collecting metrics from $collStats
    collstats: false
    ## @param metrics.collector.collstatsColls List of \<databases\>.\<collections\> to get $collStats
    collstatsColls: []
    ## @param metrics.collector.indexstatsColls List - List of \<databases\>.\<collections\> to get $indexStats
    indexstatsColls: []
    ## @param metrics.collector.collstatsLimit Number - Disable collstats, dbstats, topmetrics and indexstats collector if there are more than \<n\> collections. 0=No limit
    collstatsLimit: 0
 
  resourcesPreset: "nano"
  serviceMonitor:
    enabled: true
