[workspace]

members = [
    "apps/*",
    "shared",
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
strip = true

[profile.release-lto]
inherits = "release"
lto = "fat"

[profile.release-debug]
inherits = "release"
debug = true
strip = false

[workspace.dependencies]
shared = { path = "shared" }

# These patches are pending PRs to the upstream crates
# TODO: Remove these once the PRs are merged
[patch.crates-io]
# https://github.com/remkop22/postgres-from-row/pull/9
postgres-from-row = { git = "https://github.com/ScuffleTV/postgres-from-row.git", branch = "troy/from_fn" }
