[workspace]

members = [
    "apps/*",
    "shared",
]

resolver = "2"

[profile.release]
strip = false
debug = true
lto = "thin"

[profile.release-lto]
inherits = "release"
lto = "fat"

[workspace.dependencies]
shared = { path = "shared" }
