[workspace]

members = [
    "apps/*",
    "macros",
    "shared",
]

resolver = "2"

[profile.release]
strip = false
debug = true
lto = "thin"

[profile.release-lto]
inherits = "release"
lto = "fat"
debug = false
strip = true

[workspace.dependencies]
shared = { path = "shared" }
macros = { path = "macros" }
