[workspace]

members = [
	"apps/api",
	"apps/cdn",
	"apps/event-api",
	"apps/mongo-change-stream",
	"apps/mongo-typesense",
	"apps/reprocess-badges",
	"macros",
	"shared",
]

resolver = "2"

[profile.release-debug]
inherits = "release"
strip = false
debug = true
lto = "thin"

[profile.release-lto]
inherits = "release"
lto = "fat"
debug = false
strip = true

[workspace.dependencies]
shared = { path = "shared" }
macros = { path = "macros" }
