[package]
name = "macros"
version = "0.1.0"
edition = "2021"

#proc macro crate
[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
darling = "0.20"
proc-macro-crate = "3"
